[project]
name = "axiomkit"
version = "0.0.001"
description = "Default template for PDM package"
authors = [
    {name = "Fuqing Zhang", email = "fu.qing.zhang.work@gmail.com"},
]
dependencies = ["polars>=1.37.0", "xlsxwriter>=3.2.9"]
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
